{"name": "Попытка создания двух одинаковых курьеров возвращает \"Этот логин уже используется. Попробуйте другой.\"", "status": "passed", "steps": [{"name": "Запрос создания курьера", "status": "passed", "parameters": [{"name": "login", "value": "'cckkfuwixn'"}, {"name": "password", "value": "'pkywtrsqbz'"}, {"name": "firstname", "value": "'kdsectslvp'"}], "start": 1745013317397, "stop": 1745013317839}], "start": 1745013316572, "stop": 1745013317840, "uuid": "563fa8e9-0516-434d-9845-eb1ba7a47093", "historyId": "047ae47fba41a231025f3666a7ea0d75", "testCaseId": "047ae47fba41a231025f3666a7ea0d75", "fullName": "test.test_create_courier.TestCreateCourier#test_identical_signup_return_fail", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WM-HY9GFP70WW"}, {"name": "thread", "value": "68803-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_create_courier"}]}